### ISSUE TITLE
Add Booking Functionality

### ISSUE THREAD

**Issue by sahil-patel6** [theblazecoders/smart-car-parking-app#3]

**Comment by harshkhandeparkar** [comment]
Hi!

**Comment by sahil-patel6** [comment]
Hii

**Comment by harshkhandeparkar** [comment]
Are you working on this? If yes, I will also work.

**Comment by sahil-patel6** [comment]
Actually I have completed that feature, that's why I closed that issue

**Comment by sahil-patel6** [comment]
Currently I am working on my game so maybe we can work together later..

**Comment by harshkhandeparkar** [comment]
Sure.

**Comment by harshkhandeparkar** [comment]
Which game?

**Comment by sahil-patel6** [comment]
SOS the board game:

https://play.google.com/store/apps/details?id=com.sahilpatel.sos

**Comment by harshkhandeparkar** [comment]
Oh. You are changing it?

**Comment by sahil-patel6** [comment]
No just adding some features and fixing some bugs and optimising

**Comment by harshkhandeparkar** [comment]
Oh.

**Comment by harshkhandeparkar** [comment]
Do you remember that [this](https://theblazecoders.github.io/#about) is something that exists? :rofl:

**Comment by sahil-patel6** [comment]
What?

**Comment by harshkhandeparkar** [comment]
The website and the organization. We never did anything.

**Comment by sahil-patel6** [comment]
Yeah that is true
